# Generated by Django 5.0.3 on 2026-04-19 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('food_type', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg'), ('VEGAN', 'Vegan'), ('MIXED', 'Mixed')], max_length=10)),
                ('quantity_servings', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('allergen_notes', models.TextField(blank=True)),
                ('pickup_address', models.TextField()),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_window_start', models.DateTimeField()),
                ('pickup_window_end', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('PICKED_UP', 'Picked Up'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='donations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='donations.donation')),
            ],
        ),
    ]
