# Generated by Django 5.0.3 on 2026-04-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_email_verification_token_user_is_email_verified_and_more'),
        ('donations', '0002_alter_donation_location_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLAIMED', 'Claimed'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled')], default='CLAIMED', max_length=10)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='donations.donation')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.organization')),
            ],
        ),
    ]
